PROJECT_PATH: .
AVATAR_PATH: /media/avatar/
DEFAULT_AVATAR: /media/avatar/default.svg
IMG_MSG_PATH: /media/msg/
DEFAULT_IMG_MSG: /media/msg/default.png
PAPER_PATH: ../papers/
ACTIVATION_BASE_URL: www.example.org
INVALID_NAME_LIST:
  - default
  - admin
  - null
  - none
