name: mobook

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup SSH
        run: sudo apt install sshpass

      - name: init project
        env:
          PROJ_DIR: ${{ vars.PROJECT_DIR }}
          GIT_REPO: ${{ vars.GIT_REPOSITORY }}
        run: >
          sshpass -p ${{ secrets.PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.SSH_IP }}
          "rm -rf ${PROJ_DIR}; cd ${PROJ_DIR}; git config --global http.postBuffer 1048576000; git clone ${GIT_REPO} ${PROJ_DIR}"

      - name: establish connection
        env:
          PROJ_DIR: ${{ vars.PROJECT_DIR }}
          PORT: ${{ vars.PRODUCTION_PORT }}
        run: >
          sshpass -p ${{ secrets.PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.SSH_IP }}
          "cd ${PROJ_DIR}; killall -9 daphne; daphne -b 0.0.0.0 -p ${PORT} MoBook.asgi:application > daphne.log 2>&1 &"
