name: mobook

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Setup Rsync
        uses: GuillaumeFalourd/setup-rsync@v1.1

      - name: Check Rsync
        run: rsync --version

      - name: Setup sshpass
        run: sudo apt install sshpass

      - name: Tree
        run: tree ./

      - name: Deploy with rsync
        env:
          PROJ_DIR: ${{ vars.PROJECT_DIR }}
        run: >
          sshpass -p ${{ secrets.PASSWORD }}
          "mkdir -p ${PROJ_DIR}; rsync -avz --delete ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${PROJ_DIR}"

      - name: establish connection
        env:
          PROJ_DIR: ${{ vars.PROJECT_DIR }}
          PORT: ${{ vars.PRODUCTION_PORT }}
        run: >
          sshpass -p ${{ secrets.PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.SSH_HOST }}
          "cd ${PROJ_DIR}; killall -9 daphne; daphne -b 0.0.0.0 -p ${PORT} MoBook.asgi:application > daphne.log 2>&1 &"
