name: mobook

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: acquire permissions
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: setup SSH
        run: sudo apt install sshpass

      - name: init project
        env:
          PROJ_DIR: ${{ vars.PROJECT_DIR }}
          GIT_REPO: ${{ vars.GIT_REPOSITORY }}
        run: >
          sshpass -p ${{ secrets.PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.SSH_IP }}
          "rm -rf ${PROJ_DIR}; git clone git@github.com:BUAA-2121Unknown/MoBook-Backend.git ${PROJ_DIR}"

      - name: establish connection
        env:
          PROJ_DIR: ${{ vars.PROJECT_DIR }}
          PORT: ${{ vars.PRODUCTION_PORT }}
        run: >
          sshpass -p ${{ secrets.PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.SSH_IP }}
          "cd ${PROJ_DIR}; killall -9 daphne; daphne -b 0.0.0.0 -p ${PORT} MoBook.asgi:application > daphne.log 2>&1 &"
