name: mobook

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: setup SSH
        run: sudo apt install sshpass

      - name: init project
        env:
          PROJ_DIR: ${{ env.PROJECT_DIR }}
        run: >
          sshpass -p ${{ secrets.PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.SSH_IP }}
          "mkdir -p ${{ PROJ_DIR }}; cd ${{ PROJ_DIR }}; git config --global http.postBuffer 1048576000; git pull"

      - name: establish connection
        env:
          PROJ_DIR: ${{ env.PROJECT_DIR }}
        run: >
          sshpass -p ${{ secrets.PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.SSH_IP }}
          "cd ${ PROJ_DIR }; killall -9 daphne; daphne -b 0.0.0.0 -p ${{ env.PORT }} MoBook.asgi:application > daphne.log 2>&1 &"
